version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ./:/workspace:cached
    working_dir: /workspace/frontend
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    ports:
      - '3000:3000'
  backend:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    volumes:
      - ./:/workspace:cached
    working_dir: /workspace/backend
    command: bash -lc "dotnet run --project Backend.csproj --urls http://0.0.0.0:5000"
    ports:
      - '5000:5000'
